// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxXBWFORrn_jcw2mlzIHlTQtRkCKY5uyQ',
    appId: '1:486818900152:web:61aa47ed51ffc58119ec4d',
    messagingSenderId: '486818900152',
    projectId: 'flutter-firebase-1cd7d',
    authDomain: 'flutter-firebase-1cd7d.firebaseapp.com',
    storageBucket: 'flutter-firebase-1cd7d.appspot.com',
    measurementId: 'G-YL5LHLL7KJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3olfEULpQ9CioZqxEfIjUoi41W8ek9yg',
    appId: '1:486818900152:android:f373d8c27a19048619ec4d',
    messagingSenderId: '486818900152',
    projectId: 'flutter-firebase-1cd7d',
    storageBucket: 'flutter-firebase-1cd7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZS3r22hMGPMUg9ZL6dOFNViX7Yal8KsE',
    appId: '1:486818900152:ios:a733f2c299aa23b619ec4d',
    messagingSenderId: '486818900152',
    projectId: 'flutter-firebase-1cd7d',
    storageBucket: 'flutter-firebase-1cd7d.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZS3r22hMGPMUg9ZL6dOFNViX7Yal8KsE',
    appId: '1:486818900152:ios:1899c4e3b7cd8bdd19ec4d',
    messagingSenderId: '486818900152',
    projectId: 'flutter-firebase-1cd7d',
    storageBucket: 'flutter-firebase-1cd7d.appspot.com',
    iosBundleId: 'com.example.firebaseApp.RunnerTests',
  );
}
